# Generated by Django 3.0.5 on 2020-04-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
    ]
