# Generated by Django 3.0.5 on 2020-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grass', '0002_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassroot',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
